language: node_js
node_js:
 - "node"
dist: trusty
addons:
  sonarcloud:
    organization: "l10n3l"
    token:
      secure: "bNeWdcVznLrqlBmG8Irpzy/DEx+38T8zneKMyhzt6CGdzJpNUpP62OUaPd3e8MpZEQfUUiE5g4F4Ae63OrKQW/+dbVVmW+FNWV3c5fv8ssDa3ltpFFaBIwkoZ1nHVmHNwFAK8YUUFgmX0PLdI4VEDRZhdupyrPOrXH4yOkvL2FJtOI5F8QHoeF67hdCiIh+D/cv8C8vbotfTUviyltv+o5GRRghJkujaxkm28jVeQM+lbYKgKbSY0CZoGMBSMXoWXEF9WIdB1DY2+6xKWTKbIIejmsAuGn8Ylptig8s4i47CzPdPVO2XWF7NC8Iox3r1vA1l85r8+dM0msxXOkJzqpkOMnT0J/tJIY1pfTza3haWj50aQesXRy+mqKPjDerjEMU/KMKNGvcxXEbnKquSQL11g9YdFXiiPSQiV21Vt7h555GTLSm86cGSWaAqmuTKauKqkgKkNqUTFvJwiCcL8BaHaeR92ZW0pBSQWpXsrZ8BmMtmR2RzUuqVNSsr39PKXvvU+hPoA1J/XuAFP09eNjzV78/NL/oUugAfkxlDR9yKO9VN/nMLViNRZaJku1sVOIjtTcYi1g4FXAvI+ZI36I0pjSnRjRPYc0GQE/DsUpC3gJiMoJnoDcyDpqDpMVi7gWODp2pVZo203noK9hGqIoBCrrSu6X7rvdYMbQFIN4o="
install:
  - npm install -g nyc coveralls mocha mocha-lcov-reporter 
script:
  - npm run coverage
  - sonar-scanner
